### PR TITLE
Windows Filename issue

### PR DESCRIPTION
**Pull request by cyber-jack**
$ git clone https://github.com/peerchemist/finta
Cloning into 'finta'...
remote: Enumerating objects: 160, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 1227 (delta 84), reused 112 (delta 49), pack-reused 1067
Receiving objects: 100% (1227/1227), 522.49 KiB | 1.59 MiB/s, done.
Resolving deltas: 100% (657/657), done.
error: invalid path 'tests/data/bittrex:btc-usdt.csv'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Colon (:) is an illegal character in Windows, changed filenames so I can clone the repo.

### CODE REVIEW

**Comment by peerchemist** [comment]
Okay, I did not know ":" is illegal in Windows.

**Comment by peerchemist** [comment]
Welp, it seems this nuked all the tests. I would guess you have corrupted the datasets.

**Comment by cyber-jack** [comment]
I only changed the filenames? Both the filename and the line in code that refers to them.

**Comment by peerchemist** [comment]
Upon further inspection it seems your PSAR commit is what is nuking the tests. I am digging in to see what is going on.
I presume PSAR is writing into ohlc dataset rather than just using it's own internal numbers.

Give it a try maybe you spot what is going on.

**Comment by cyber-jack** [comment]
I closed pull request https://github.com/peerchemist/finta/pull/76 as I am still working on the PSAR function. Due to the nature of how PSAR is calculated the function will need further tweaking. I didn't have time to tweak it, can we revert the PSAR commit for now? I'll open another PR when I finished tweaking the function and tested it properly (next few days hopefully).

**Comment by peerchemist** [comment]
Just push patch onto master when done.

**Pull request merged**
