### PR TITLE
feat(BBANDS): added possibility to change the factor of the standard …

### PR DESCRIPTION
**Pull request by Jrenk**
I added the possibility to change the multiplier of the standard deviation in the Bollinger Bands (BBANDS) function. It was hard coded to 2 before.

### CODE REVIEW

**Comment by peerchemist** [comment]
Your patch also does code formatting. Please don't do that.

**Comment by Jrenk** [comment]
This was all done by https://github.com/psf/black.

**Comment by Jrenk** [comment]
Should I still remove it?

**Comment by peerchemist** [comment]
Please, I'll do reformat in the near future. Just push the BBANDS patch.

**Comment by Jrenk** [comment]
Done.

**Pull request merged**
